[package]
name = "mdbook-extensions"
version = "0.1.0"
edition = "2024"

[dependencies]
mdbook = { version = "0.4.52" }
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
semver = "1.0.26"
serde_json = "1.0.143"
serde = "1.0.219"
serde_yaml_ng = "0.10.0"
regex = "1.11.3"
