name: Build and Deploy
on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mdbook
        run: cargo install mdbook --git https://github.com/hg-anssi/mdBook.git --rev c5a35b9296c6d5e48570e30022bd69403050a9f4 --locked
      - name: Install mdbook-checklist
        run: cargo install --path ./mdbook-checklist --locked
      - name: Install mdbook-code-align
        run: cargo install --path ./mdbook-code-align --locked
      - name: Install mdbook-extensions
        run: cargo install --path ./mdbook-extensions --locked
      - name: Build EN version
        run: |
          ./lang.sh en
          mdbook build
      - name: Build FR version
        run: |
          ./lang.sh fr
          mdbook build
      - name: Move FR version
        run: mv book/fr/html book/en/html/fr
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: book/en/html
          clean: true
