name: Build and Deploy
on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Build document
        uses: nix build .
      - name: Copy result into local directory
        run: cp -r result/book .
      - name: Move FR version
        run: mv book/fr/html book/en/html/fr
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: book/en/html
          clean: true
